// Iconos Tabler Icons (ti) centralizados

export const ICONS = {
  LOADER: "ti ti-loader-2",
  CLOSE: "ti ti-x",
  PLUS: "ti ti-plus",
  CAR: "ti ti-car",
  CAR_OFF: "ti ti-car-off",
  CAR_CRASH: "ti ti-car-crash",
  PENCIL: "ti ti-pencil",
  SEARCH: "ti ti-search",
  TRASH: "ti ti-trash",
  ALERT_TRIANGLE: "ti ti-alert-triangle",
  TOOL: "ti ti-tool",
  SAVE: "ti ti-device-floppy",
  ALERT_CIRCLE: "ti ti-alert-circle",
  CALENDAR: "ti ti-calendar",
  CHEVRON_DOWN: "ti ti-chevron-down",
  LOCK: "ti ti-lock",
  CHECK: "ti ti-check",
  ARROW_LEFT: "ti ti-arrow-left",
  ARROW_RIGHT: "ti ti-arrow-right",
  HOME: "ti ti-home",
  USER: "ti ti-user",
  USER_SEARCH: "ti ti-user-search",
  USER_CHECK: "ti ti-user-check",
  LIST: "ti ti-list",
  COMPONENTS: "ti ti-components",
  MAIL: "ti ti-mail",
  MAIL_CHECK: "ti ti-mail-check",
  PHONE: "ti ti-phone",
  RIPPLE: "ti ti-ripple",
  SETTINGS_2: "ti ti-settings-2",
  CIRCLE: "ti ti-circle",
  CIRCLE_CHECK: "ti ti-circle-check",
  CHEVRON_RIGHT: "ti ti-chevron-right",
  CHEVRON_LEFT: "ti ti-chevron-left",
  FILTER_OFF: "ti ti-filter-off",
  REFRESH: "ti ti-refresh",
  HISTORY: "ti ti-history",
  EYE: "ti ti-eye",
  TOOLS: "ti ti-tools",
  FILE_PLUS: "ti ti-file-plus",
  FILE_TEXT: "ti ti-file-text",
  FILE: "ti ti-file",
  LIST_SEARCH: "ti ti-list-search",
  CLIPBOARD: "ti ti-clipboard",
  CLIPBOARD_LIST: "ti ti-clipboard-list",
  CLIPBOARD_OFF: "ti ti-clipboard-off",
  LOCK_CHECK: "ti ti-lock-check",
  ADJUSTMENTS_HORIZONTAL: "ti ti-adjustments-horizontal",
  PLAYER_PAUSE: "ti ti-player-pause",
  BAN: "ti ti-ban",
  MOOD_EMPTY: "ti ti-mood-empty",
  RECEIPT: "ti ti-receipt",
  PHOTO_OFF: "ti ti-photo-off",
  FLAG: "ti ti-flag",
  MENU_2: "ti ti-menu-2",
  LOGOUT: "ti ti-logout",
  SEND: "ti ti-send",
  ROAD_SIGN: "ti ti-road-sign",
  DOWNLOAD: "ti ti-download",
  PLAY: "ti ti-play",
  BOX: "ti ti-box",
  BOLT: "ti ti-bolt",
};

// Mapa de categoría → icono (duplicado en CardPieza y piezas/index)
export const ICONOS_CATEGORIA = {
  carrocería: ICONS.CAR,
  vidrios: ICONS.RIPPLE,
  accesorios: ICONS.SETTINGS_2,
  rodado: ICONS.CIRCLE,
};
